export const SET_WEBSOCKET = 'SET_WEBSOCKET';
export const SET_CURRENT_SOURCE = 'SET_CURRENT_SOURCE';
export const SET_CURRENT_STATION = 'SET_CURRENT_STATION';
export const SET_LIST_ITEMS = 'SET_LIST_ITEMS';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const SET_HOME_ADDRESS = 'SET_HOME_ADDRESS';
export const SET_BRIGHTNESS = 'SET_BRIGHTNESS';